# Generated by Django 3.1.2 on 2020-11-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
