# Generated by Django 3.1.2 on 2020-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20201101_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_given',
            field=models.IntegerField(default=0),
        ),
    ]
