# Generated by Django 3.1.3 on 2020-11-03 01:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20201102_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_published',
            field=models.CharField(blank=True, default='', max_length=600, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
